os: linux
language: php
dist: trusty
env:
  global:
    - XDEBUG_MODE=coverage

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml


after_script:
  - vendor/bin/coveralls --verbose
